build-backend:
  runs-on: ubuntu-latest
  services:
    mysql:
      image: mysql:8.0
      env:
        MYSQL_DATABASE: donnees
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      ports:
        - 3308:3306
      options: >-
        --health-cmd="mysqladmin ping --silent" 
        --health-start-period=30s 
        --health-retries=5 
        --health-timeout=10s
  env:
    SKIP_TESTS: "false"
    SPRING_PROFILES_ACTIVE: dev
    SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3308/donnees?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    SPRING_DATASOURCE_USERNAME:  ${{ secrets.MYSQL_USERNAME }}
    SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: "18"
        distribution: "adopt"
        cache: maven

    - name: Wait for MySQL to be Ready
      run: sleep 30

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-

    - name: Install Dependencies
      working-directory: backend
      run: mvn clean install -DskipTests 

    - name: Run Backend Tests
      if: env.SKIP_TESTS != 'true'
      working-directory: backend
      run: mvn test

    - name: Build Backend Docker Image
      run: docker build -t meschebajordy/innotech-spring-boot-backend:v1 ./backend

    - name: Save Docker Image
      run: docker save -o backend-image.tar meschebajordy/innotech-spring-boot-backend:v1

    - name: Upload Backend Image
      uses: actions/upload-artifact@v4
      with:
        name: backend-image
        path: backend-image.tar
